events {}

http {
    upstream keycloak {
        server keycloak:8080;  # Points to the Keycloak container
    }

    server {
        listen 80;

        # Enable access and error logging
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log debug;

        # Sub filter to rewrite response URLs containing /realms to /domains
        sub_filter_once off;  # Apply sub_filter for every occurrence, not just the first one
        sub_filter_types *;  # Apply the sub_filter to all types of responses, including HTML, JSON, etc.
        sub_filter '/realms/' '/domains/';

        # Serve /realms as /domains
        location /domains/ {
            rewrite ^/domains/(.*)$ /realms/$1 break;
            proxy_pass http://keycloak;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Preserve cookies
            proxy_set_header Cookie $http_cookie;
            proxy_pass_header Set-Cookie;
        }

        # General proxy pass to Keycloak for other paths
        location / {
            proxy_pass http://keycloak;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Preserve cookies
            proxy_set_header Cookie $http_cookie;
            proxy_pass_header Set-Cookie;
        }
    }
}
